insert into REVIEW (id, book_id, user_id, review, rating) values (1, 20, 9, 'lorem ipsum dolor sit amet consectetuer adipiscing elit proin risus', 3);
insert into REVIEW (id, book_id, user_id, review, rating) values (2, 15, 4, 'quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus', 5);
insert into REVIEW (id, book_id, user_id, review, rating) values (3, 1, 2, 'vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus', 3);
insert into REVIEW (id, book_id, user_id, review, rating) values (4, 5, 10, 'vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum', 4);
insert into REVIEW (id, book_id, user_id, review, rating) values (5, 15, 18, 'sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus', 4);
insert into REVIEW (id, book_id, user_id, review, rating) values (6, 6, 16, 'quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus', 2);
insert into REVIEW (id, book_id, user_id, review, rating) values (7, 13, 1, 'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci', 4);
insert into REVIEW (id, book_id, user_id, review, rating) values (8, 5, 1, 'et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida', 4);
insert into REVIEW (id, book_id, user_id, review, rating) values (9, 14, 17, 'euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis', 2);
insert into REVIEW (id, book_id, user_id, review, rating) values (10, 2, 8, 'quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec', 3);
insert into REVIEW (id, book_id, user_id, review, rating) values (11, 9, 18, 'vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in', 2);
insert into REVIEW (id, book_id, user_id, review, rating) values (12, 1, 5, 'pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac', 1);
insert into REVIEW (id, book_id, user_id, review, rating) values (13, 13, 2, 'ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec', 2);
insert into REVIEW (id, book_id, user_id, review, rating) values (14, 3, 19, 'amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non', 5);
insert into REVIEW (id, book_id, user_id, review, rating) values (15, 10, 8, 'sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor', 3);
insert into REVIEW (id, book_id, user_id, review, rating) values (16, 20, 10, 'nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a', 2);
insert into REVIEW (id, book_id, user_id, review, rating) values (17, 16, 2, 'dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 2);
insert into REVIEW (id, book_id, user_id, review, rating) values (18, 6, 6, 'enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet', 2);
insert into REVIEW (id, book_id, user_id, review, rating) values (19, 9, 3, 'morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id', 1);
insert into REVIEW (id, book_id, user_id, review, rating) values (20, 3, 7, 'aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras', 1);
insert into REVIEW (id, book_id, user_id, review, rating) values (21, 17, 5, 'nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a', 4);
insert into REVIEW (id, book_id, user_id, review, rating) values (22, 10, 3, 'in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius', 4);
insert into REVIEW (id, book_id, user_id, review, rating) values (23, 2, 5, 'duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus', 3);
insert into REVIEW (id, book_id, user_id, review, rating) values (24, 11, 11, 'convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas', 2);
insert into REVIEW (id, book_id, user_id, review, rating) values (25, 10, 5, 'volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum', 4);
insert into REVIEW (id, book_id, user_id, review, rating) values (26, 16, 16, 'justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue', 5);
insert into REVIEW (id, book_id, user_id, review, rating) values (27, 17, 19, 'purus phasellus in felis donec semper sapien a libero nam dui', 4);
insert into REVIEW (id, book_id, user_id, review, rating) values (28, 19, 2, 'vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra', 4);
insert into REVIEW (id, book_id, user_id, review, rating) values (29, 18, 1, 'nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in', 3);
insert into REVIEW (id, book_id, user_id, review, rating) values (30, 14, 8, 'auctor gravida sem praesent id massa id nisl venenatis lacinia aenean', 3);
insert into REVIEW (id, book_id, user_id, review, rating) values (31, 3, 17, 'malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin', 4);
insert into REVIEW (id, book_id, user_id, review, rating) values (32, 3, 16, 'nibh in lectus pellentesque at nulla suspendisse potenti cras in', 4);
insert into REVIEW (id, book_id, user_id, review, rating) values (33, 4, 11, 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur', 5);
insert into REVIEW (id, book_id, user_id, review, rating) values (34, 5, 6, 'duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede', 2);
insert into REVIEW (id, book_id, user_id, review, rating) values (35, 10, 3, 'bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris', 2);
insert into REVIEW (id, book_id, user_id, review, rating) values (36, 17, 15, 'suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus', 2);
insert into REVIEW (id, book_id, user_id, review, rating) values (37, 4, 2, 'eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et', 2);
insert into REVIEW (id, book_id, user_id, review, rating) values (38, 19, 20, 'montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id', 3);
insert into REVIEW (id, book_id, user_id, review, rating) values (39, 20, 18, 'turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa', 3);
insert into REVIEW (id, book_id, user_id, review, rating) values (40, 11, 4, 'mattis egestas metus aenean fermentum donec ut mauris eget massa', 4);
insert into REVIEW (id, book_id, user_id, review, rating) values (41, 12, 12, 'urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla', 3);
insert into REVIEW (id, book_id, user_id, review, rating) values (42, 13, 17, 'amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur', 5);
insert into REVIEW (id, book_id, user_id, review, rating) values (43, 14, 9, 'a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue', 5);
insert into REVIEW (id, book_id, user_id, review, rating) values (44, 5, 13, 'vel sem sed sagittis nam congue risus semper porta volutpat quam', 1);
insert into REVIEW (id, book_id, user_id, review, rating) values (45, 6, 20, 'maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac', 3);
insert into REVIEW (id, book_id, user_id, review, rating) values (46, 3, 13, 'felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam', 5);
insert into REVIEW (id, book_id, user_id, review, rating) values (47, 16, 17, 'aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi', 5);
insert into REVIEW (id, book_id, user_id, review, rating) values (48, 15, 14, 'nulla eget eros elementum pellentesque quisque porta volutpat erat quisque', 1);
insert into REVIEW (id, book_id, user_id, review, rating) values (49, 16, 6, 'commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id', 5);
insert into REVIEW (id, book_id, user_id, review, rating) values (50, 1, 13, 'vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent', 1);
insert into REVIEW (id, book_id, user_id, review, rating) values (51, 8, 3, 'nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt', 2);
insert into REVIEW (id, book_id, user_id, review, rating) values (52, 17, 5, 'primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus', 1);
insert into REVIEW (id, book_id, user_id, review, rating) values (53, 16, 6, 'primis in faucibus orci luctus et ultrices posuere cubilia curae duis', 5);
insert into REVIEW (id, book_id, user_id, review, rating) values (54, 15, 14, 'duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at', 2);
insert into REVIEW (id, book_id, user_id, review, rating) values (55, 6, 3, 'congue risus semper porta volutpat quam pede lobortis ligula sit amet', 4);
insert into REVIEW (id, book_id, user_id, review, rating) values (56, 14, 18, 'magnis dis parturient montes nascetur ridiculus mus etiam vel augue', 5);
insert into REVIEW (id, book_id, user_id, review, rating) values (57, 3, 1, 'luctus nec molestie sed justo pellentesque viverra pede ac diam', 1);
insert into REVIEW (id, book_id, user_id, review, rating) values (58, 20, 13, 'amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim', 4);
insert into REVIEW (id, book_id, user_id, review, rating) values (59, 3, 10, 'neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel', 5);
insert into REVIEW (id, book_id, user_id, review, rating) values (60, 10, 18, 'nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed', 5);
