insert into User (id, email, password, name) values (1, 'erosenstock0@umich.edu', 'h8kvfeA', 'Elfie');
insert into User (id, email, password, name) values (2, 'rreeme1@phoca.cz', 'wU9ajy8P', 'Roxana');
insert into User (id, email, password, name) values (3, 'smckern2@hhs.gov', '2bcvQRIX', 'Stefa');
insert into User (id, email, password, name) values (4, 'fmcphillips3@hubpages.com', 'J9xsOMheAH54', 'Fredrick');
insert into User (id, email, password, name) values (5, 'aboyford4@ibm.com', 'b48Hy7EV', 'Aidan');
insert into User (id, email, password, name) values (6, 'kleabeater5@miitbeian.gov.cn', 'ZKc1972', 'Kathye');
insert into User (id, email, password, name) values (7, 'ssavatier6@elegantthemes.com', 'ZzCkUPQp6D', 'Sari');
insert into User (id, email, password, name) values (8, 'tewells7@uol.com.br', 'L5HrPeD1', 'Tades');
insert into User (id, email, password, name) values (9, 'gsansum8@seesaa.net', '3Yj6ARt6ORA', 'Gwenny');
insert into User (id, email, password, name) values (10, 'fdunkersley9@moonfruit.com', 'CNvbDoIhN4l', 'Fabien');
insert into User (id, email, password, name) values (11, 'dpilleya@reverbnation.com', 'ECus9qH', 'Daisie');
insert into User (id, email, password, name) values (12, 'ttoyeb@walmart.com', 'KDdiuZNF1j', 'Toni');
insert into User (id, email, password, name) values (13, 'wgallegosc@home.pl', 'I9UDJavY', 'Worth');
insert into User (id, email, password, name) values (14, 'jaired@wordpress.org', 'I3sqHTdu8YGD', 'Jourdan');
insert into User (id, email, password, name) values (15, 'hpetigrewe@wix.com', '52r7lrxeb', 'Hasty');
insert into User (id, email, password, name) values (16, 'lvenesf@accuweather.com', 'k8RY5X7o', 'Leonora');
insert into User (id, email, password, name) values (17, 'hwalmsleyg@msn.com', 'LKT1G0rNIX', 'Harriott');
insert into User (id, email, password, name) values (18, 'hlaingeh@irs.gov', '5USun7M5', 'Helga');
insert into User (id, email, password, name) values (19, 'mhafneri@csmonitor.com', 'wl0QJSu', 'Merle');
insert into User (id, email, password, name) values (20, 'igerckej@sina.com.cn', '9ZyNstRclp', 'Issy');
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (13, 5);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (19, 8);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (15, 1);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (7, 11);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (2, 5);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (9, 8);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (6, 4);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (3, 14);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (18, 10);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (14, 20);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (8, 3);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (14, 6);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (6, 19);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (3, 13);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (12, 9);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (7, 6);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (10, 13);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (14, 1);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (8, 5);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (2, 19);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (5, 18);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (19, 6);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (2, 6);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (6, 8);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (5, 1);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (4, 19);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (17, 19);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (1, 4);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (5, 15);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (14, 2);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (13, 4);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (12, 14);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (11, 5);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (1, 11);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (12, 7);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (16, 14);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (3, 15);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (8, 13);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (1, 19);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (20, 11);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (14, 16);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (20, 2);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (7, 15);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (7, 11);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (6, 8);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (1, 7);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (7, 12);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (6, 10);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (20, 10);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (14, 1);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (10, 12);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (14, 2);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (16, 12);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (6, 19);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (17, 8);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (18, 17);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (5, 17);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (4, 7);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (19, 2);
insert into USER_BOOKS_READ (USER_ID, BOOKS_READ) values (8, 10);
